spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: petbot

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
telegram:
  bot:
    # noinspection SpringBootApplicationYaml
    username: ${TELEGRAM_BOT_USERNAME:PetBot}
    # noinspection SpringBootApplicationYaml
    token: ${TELEGRAM_BOT_TOKEN}

